### ISSUE TITLE
arrow support in vetiver

### ISSUE THREAD

**Issue by isabelizimm** [rstudio/vetiver-python#103]
Trying to figure out how to support arrow in vetiver. What would this look like? Where does it make sense to implement?

**Comment by juliasilge** [comment]
In vetiver for R, I think we use arrow right now [only in storing monitoring metrics](https://github.com/rstudio/vetiver-r/blob/973950bd03c8c0f177e0fee1c66c1c097ddd6df9/R/monitor.R#L173).

**Comment by isabelizimm** [comment]
possible locations:
- at the model level: doesn't make sense yet since most modeling frameworks don't support arrow (?)
- ptype: could add in option to save as parquet
- predict: could accept, but then would have to convert to pandas 
- pinning metrics: right now you can save as parquet, but not if you are coming from polars https://github.com/rstudio/pins-python/issues/153

from this list, it is both possible and useful to look into arrow support at `ptype` and `predict`, following up with pinning later?
