### ISSUE TITLE
log python version in `vetiver_pin_write`

### ISSUE THREAD

**Issue by isabelizimm** [rstudio/vetiver-python#115]
After talking with some community members, a common point of failure for them was a mismatch in python version when moving models around (even if other dependencies are logged). It might be a useful addition in the metadata to track this as well.

**Comment by machow** [comment]
Oh interesting--do you know what they see when they hit an error due to mismatched python versions? Is it something related to loading a pickle/joblib object? How do they know it is due to a python version mismatch?

**Comment by isabelizimm** [comment]
I believe it was mostly around reproducing environments between development/staging/production. I don't remember the specific breaking issue, but I do know it stemmed from a desire to ensure identical envs when shifting between locations
