### ISSUE TITLE
wrap `rsconnect` for vetiver-specific deployment

### ISSUE THREAD

**Issue by isabelizimm** [rstudio/vetiver-python#15]
Similar to [Vetiver-R](https://github.com/tidymodels/vetiver-r/blob/main/R/deploy-rsconnect.R), help users deploy to RSConnect in a vetiver-aware way. Currently, users are able to deploy to connect using the `rsconnect-python` package via `deploy_python_fastapi`, but we would like to make this more clear and discoverable for vetiver users. This functionality can come from a thin wrapper around [rsconnect-python](https://github.com/rstudio/rsconnect-python/blob/cc1aaefedcb110a0279bd3b6867ce1317ad3ec7a/rsconnect/actions.py#L752).

**Comment by gsingh91** [comment]
will appreciate if we can have this available before conf to include in the bikeshare demo
