### ISSUE TITLE
No vetiver_pin_read method

### ISSUE THREAD

**Issue by josho88** [rstudio/vetiver-python#156]
Hi - I don't seem to be able to import the vetiver_pin_read function from the latest development version of this package.

**Describe the bug**
When importing vetiver_pin_read, an error message is displayed: 

```
AttributeError: module 'vetiver' has no attribute 'vetiver_pin_read'
```

Does vetiver_pin_read need to be added to `__init__.py` ?

Thanks!

**Comment by isabelizimm** [comment]
Hey there, thanks for the report @josho88! The function `vetiver_pin_read` was deprecated and then removed in favor of a more pythonic `VetiverModel.from_pin(board, pin_name)` as a clearer description that the results of the function are a VetiverModel object created from that pin. Here's an [example of a round trip pin](https://vetiver.rstudio.com/get-started/version.html#store-and-version-your-model). Let me know if you have any questions about using this method!

**Comment by josho88** [comment]
Ah I see, thanks that makes sense!
