### ISSUE TITLE
Conda parameter for rsconnect-python is being deprecated

### ISSUE THREAD

**Issue by sagerb** [rstudio/vetiver-python#196]
Vetiver-python codebase should remove this parameter and not pass it into the `deploy_python_fastapi` method exposed by the `rsconnect-python` package.

This has been deprecated because:
>Experimental support for Conda environment was added to rsconnect-python. Connect does not support restoring Conda environments. 

I will be submitting a PR shortly.

**Comment by isabelizimm** [comment]
Thanks so much for keeping vetiver up to date with `rsconnect-python` 🙌
