### ISSUE TITLE
On documentation

### ISSUE THREAD

**Issue by has2k1** [rstudio/vetiver-python#39]
- [x] Add link to documentation in the about section on the main page
- [x] Add link to documentation in the readme
- [x] Have 2 documentation destinations
  - [x] Released / stable
  - [x] Unreleased / main branch / latest
  - [ ] Make the versioning of the package under development clearly show that it is not a released version
- [x] Prevent docs workflows initiated by PRs (esp. from contributors) from attempting to push to the gh-pages branch. _Currently this happens and is indicated as a failed test_

**Comment by isabelizimm** [comment]
I believe all tasks of this are complete with #93 . Feel free to reopen this or new issues for further docs updates!
