### ISSUE TITLE
Use tags for versioning

### ISSUE THREAD

**Issue by has2k1** [rstudio/vetiver-python#62]
[setuptools_scm](https://github.com/pypa/setuptools_scm)

With tagged versioning you have each commit as a distinct version and can have different documentation for stable & development.

**Comment by machow** [comment]
In case it's useful -- there's a github action job to deploy to PyPI in pins here!: https://github.com/rstudio/pins-python/blob/main/.github/workflows/ci.yml#L257-L276

**Comment by isabelizimm** [comment]
closed with #86
