### ISSUE TITLE
allow rewriting py file

### ISSUE THREAD

**Issue by gsingh91** [rstudio/vetiver-python#66]
**Is your feature request related to a problem? Please describe.**
while using the `vetiver_write_app` function, it does not allow rewriting the file if the file already exists

**Describe the solution you'd like**
Allow rewriting the file

**Describe alternatives you've considered**
For now, we manually delete the file first before rerunning the function.

**Additional context**

**Comment by isabelizimm** [comment]
Thank you for this feedback 🙌  I had chosen to not allow rewriting to not have people accidentally rewriting/deploying app files without noticing. However, I can add an argument to allow for rewriting, so users can chose to turn off this safety net!

**Comment by isabelizimm** [comment]
I looped this into #65 since `vetiver_write_app` (now `vetiver.write_app`) got a refresh. Setting `overwrite=True` should give you the desired behavior!
