### ISSUE TITLE
model monitoring

### ISSUE THREAD

**Issue by isabelizimm** [rstudio/vetiver-python#75]
issue for tracking purposes 🥳 

main monitoring functions
- [x] `vetiver.compute_metrics`
- [x] `vetiver.pin_metrics`
- [x] `vetiver.plot_metrics`

**Comment by machow** [comment]
### vetiver compute metrics

<img width="571" alt="image" src="https://user-images.githubusercontent.com/2574498/176908907-9e0f31f7-7fd0-4b26-a717-5b4be2a05297.png">


<img width="561" alt="image" src="https://user-images.githubusercontent.com/2574498/176908835-f0022a44-0746-419b-8a4d-c168240def11.png">

* the grain seems to be .index and .metric
* .index - the rolled up date used
* .n - number of rows used in rollup
* .metric - kind metric (from hardhat)
* .estimator - group of estimators (e.g. standard for continuous variables? other values are "binary", etc..)

**Comment by juliasilge** [comment]
This looks like it is done to me! 👀 Is it ready to be closed?

**Comment by isabelizimm** [comment]
yes! closed with #82 and #76
