### ISSUE TITLE
Example dropdown improvement

### ISSUE THREAD

**Issue by gsingh91** [rstudio/vetiver-python#85]
**Describe the bug**
Not sure if this is a bug, but wanted to capture it here. In the docs page of the API, the drop down under the Examples section has same values `ptype` for both single and batch predictions.

**Expected behavior**
Different names for different types of predictions(single/batch etc)

**Screenshots**
<img width="239" alt="Screen Shot 2022-07-07 at 7 35 22 PM" src="https://user-images.githubusercontent.com/12013337/177889533-3affb019-5bf8-48e4-8806-30d9704de96c.png">

**Comment by isabelizimm** [comment]
This is coming from the [type hint](https://github.com/rstudio/vetiver-python/blob/9f43e8d5fa46af571487cc0790f11b356f19737a/vetiver/server.py#L69) for the endpoint. The way to update this is name is the make a type called "batch" that is equivalent to a ptype (but not a list of ptypes). This seems a bit awkward. A possibility is remove a dictionary as a type hint. Then, there would be no dropdown, and the example would be a list of dicts (which can be used for single or batch prediction). This would better match the R visual API documentation, which has a list.
