### ISSUE TITLE
change monitoring column from `estimate` to `score`

### ISSUE THREAD

**Issue by isabelizimm** [rstudio/vetiver-python#90]
In monitoring, we have 4 output columns for `compute_metrics`: `index`, `n`, `metric`, and `estimate`. 

Is `estimate` the right label? It is not an estimated value, rather it is a specific, calculated value. It might be confusing outside of the dataframe (ie, in plots created).

CC: @juliasilge

**Comment by juliasilge** [comment]
On the R side, this comes from yardstick, where `.estimate` means an [estimate](https://en.wikipedia.org/wiki/Estimator) in the statistical sense (like estimator, estimand, estimate). I know R folks tend to be much more statistically inclined so maybe we should discuss this or document it more clearly on one or both sides.

What would you expect to see for column names in a dataframe like this with scikit-learn metrics, with one row per metric?

``` r
library(yardstick)
#> For binary classification, the first factor level is assumed to be the event.
#> Use the argument `event_level = "second"` to alter this as needed.
metrics(two_class_example, truth, predicted, Class1)
#> # A tibble: 4 × 3
#>   .metric     .estimator .estimate
#>   <chr>       <chr>          <dbl>
#> 1 accuracy    binary         0.838
#> 2 kap         binary         0.675
#> 3 mn_log_loss binary         0.328
#> 4 roc_auc     binary         0.939
```

<sup>Created on 2022-07-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by isabelizimm** [comment]
Ah, that history makes sense for the labels! I think metric is expected, and `.estimate` would be `score`. For `.estimator`, I don't know if there's really a direct translation for all the metrics. For example, I would think maybe [regression metrics](https://scikit-learn.org/stable/modules/model_evaluation.html#regression-metrics) could return the `multioutput` kw, but not all functions have this/similar arguments.

For now, I'll add notes in the docs about the column naming. I think the current name gives the best one-size-fits-all explanation of the columns. With the statistical context in mind, this makes a lot more sense-- thank you!
